services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - internal
networks:
  internal:
    driver: bridge
